version: '3'
services:
  bar-db:
    image: postgres:12.0-alpine
    volumes:
      - bar_postgres_data:/var/lib/postgresql/data/
    environment:
      # https://www.postgresql.org/docs/current/libpq-envars.html, подгружаются из .env
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
  
  rabbitmq:
    image: rabbitmq:3.11.5-alpine
    restart: always
    
  bar-admin-bot:
    build: ./
    command: [sh, -c, "python manage.py makemigrations db &&
                       python manage.py migrate &&
                       cd admin &&
                       python bot.py"]
    depends_on:
      - bar-db
    restart: always
  
  bar-client-bot:
    build: ./
    command: [sh, -c, "cd client &&
                       python bot.py"]
    depends_on:
      - bar-db
      - bar-admin-bot
    restart: always

volumes:
  bar_postgres_data: